export const DEFAULT_LANGUAGE = "en";

export const translations: Record<string, Record<string, string>> = {
  "zh-CN": {
    "app.title": "GitHub Stars 笔记展",
    "app.subtitle": "我的 GitHub Stars 收藏与笔记",
    "search.placeholder": "搜索仓库名称、简介、笔记...",
    "stats.totalStars": "共 {count} 个项目",
    "stats.categories": "{count} 个分类",
    "sidebar.toc": "目录",
    "sidebar.all": "全部",
    "language.switch": "English",
    "entry.stars": "{count} 星",
    "entry.language": "语言",
    "entry.topics": "主题",
    "entry.aiIntro": "AI 简介",
    "entry.description": "项目简介",
    "entry.userNotes": "我的笔记",
    "entry.updated": "更新于",
    "time.justNow": "刚刚",
    "empty.title": "没有找到匹配的仓库",
    "empty.description": "试试调整搜索词或清空筛选条件",
    "pagination.prev": "上一页",
    "pagination.next": "下一页",
    "pagination.page": "第 {page} 页，共 {total} 页",
    "pagination.pagePrefix": "第",
    "pagination.pageSuffix": "页，共 {total} 页",
    "pagination.perPage": "每页显示",
    "footer.generated": "本页由 {link} 生成",
    "footer.project": "gh-starboard",
    "footer.refreshed": "信息据上次刷新已有 {time}",
    "theme.auto": "跟随系统",
    "theme.dark": "暗色",
    "theme.light": "亮色",
    "sort.starred": "添加顺序",
    "sort.stars": "按星标数",
    "sort.updated": "按更新时间",
    "sort.name": "按名称",
    "error.loadFailed": "数据加载失败",
    "error.retry": "重试",
    "backToTop": "回到顶部",
    "filter.min": "最小",
    "filter.max": "最大",
  },
  en: {
    "app.title": "GitHub Stars Notes",
    "app.subtitle": "My GitHub Stars Collection & Notes",
    "search.placeholder": "Search repos, descriptions, notes...",
    "stats.totalStars": "{count} Stars",
    "stats.categories": "{count} Categories",
    "sidebar.toc": "Contents",
    "sidebar.all": "All",
    "language.switch": "中文",
    "entry.stars": "{count} stars",
    "entry.language": "Language",
    "entry.topics": "Topics",
    "entry.aiIntro": "AI Intro",
    "entry.description": "Description",
    "entry.userNotes": "My Notes",
    "entry.updated": "Updated",
    "time.justNow": "just now",
    "empty.title": "No matching repositories",
    "empty.description": "Try adjusting your search terms or clearing filters",
    "pagination.prev": "Previous",
    "pagination.next": "Next",
    "pagination.page": "Page {page} of {total}",
    "pagination.pagePrefix": "Page",
    "pagination.pageSuffix": "of {total}",
    "pagination.perPage": "Per page",
    "footer.generated": "Generated by {link}",
    "footer.project": "gh-starboard",
    "footer.refreshed": "Data refreshed {time} ago",
    "theme.auto": "Auto",
    "theme.dark": "Dark",
    "theme.light": "Light",
    "sort.starred": "Star order",
    "sort.stars": "By stars",
    "sort.updated": "By updated",
    "sort.name": "By name",
    "error.loadFailed": "Failed to load data",
    "error.retry": "Retry",
    "backToTop": "Back to top",
    "filter.min": "Min",
    "filter.max": "Max",
  },
};

export const LANGUAGE_LABELS: Record<string, string> = {
  "zh-CN": "中文",
  en: "English",
};

export function getLanguageLabel(code: string): string {
  if (LANGUAGE_LABELS[code]) return LANGUAGE_LABELS[code];
  try {
    const names = new Intl.DisplayNames([code], { type: "language" });
    return names.of(code) || code;
  } catch {
    try {
      const names = new Intl.DisplayNames(["en"], { type: "language" });
      return names.of(code) || code;
    } catch {
      return code;
    }
  }
}
